<a href="https://colab.research.google.com/github/Tajyu/sm11/blob/master/py_modules/py_module_1_numpy_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## python module 1. numpy



---



#### 라이브러리를 import 시키는 방법 4가지

**파이썬 코드에서 라이브러리를 import 시키는 방식**은 아래와 같이 4가지로 나눌 수 있다.



1.   라이브러리의 이름을 바로 import하는 방식
         예) import numpy
         이렇게 import를 하면 해당 라이브러리의 풀네임을 이용하여 필요한 API를 호출할 수 있음
         
2.   라이브러리의 별명을 지정하는 방식
         예) import numpy as np
         가장 일반적인 방식임
         a = np.array()
3.   from을 이용하는 방식

         from을 이용하면 해당 API의 이름을 쓰지 않고 API를 바로 쓸 수 있다는 장점이 있음
         from numpy import array, arange
         a = array()
         an = arange(10)

         
4.   필요한 라이브러리에 모든 API를 사용
         예) from numpy import *
            이 경우에도 from을 사용하여 직접 필요한 API를 기술함





##### 첫 번째 방식 - 라이브러리의 이름을 바로 import하는 방식

In [0]:
# 1. 라이브러리의 이름을 바로 import하는 방식

import numpy

a1 = numpy.array([1,2])

print("a1 = ", a1, ", type = ", type(a1))

('a1 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


##### 두 번째 방식 - 라이브러리의 별명을 지정하는 방식

In [1]:
# 2. 라이브러리의 별명을 지정하는 방식

import numpy as np

a2 = np.array([1,2])

print("a2 = ", a2, ", type = ", type(a2))

('a2 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


예) numpy라는 라이브러리를 as 다음에 나오는 np로 지정

##### 세 번째 방식 - from을 이용하는 방식

In [0]:
# 3. from을 이용하는 방식

from numpy import array

a3 = array([1, 2])

print("a3 = ", a3, ", type = ", type(a3))

('a3 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


numpy 라이브러리에 속해있는 array API를 위의 첫 번째 및 두 번째 예에서처럼 numpy.array 또는 np.array 라고 하지 않고, 바로 array를 사용

> => 즉, numpy.array가 아닌 array로 바로 사용 가능



##### 네 번째 방식 - 필요한 라이브러리에 모든 API를 사용

In [2]:
# 4. 필요한 라이브러리에 모든 API를 사용

from numpy import *                   # * 사용하지않으면 

result = exp(1) + log(1.7) + sqrt(2)  # np.exp, np.log, np.sqrt등 계속 np를 붙여줘야한다.

print("result = ", result, ", type = ", type(result))

a4 = array(range(1,5)).reshape(2,2)

print("a4 = ", a4, ", type = ", type(a4))

('result = ', 4.663123641894311, ', type = ', <type 'numpy.float64'>)
('a4 = ', array([[1, 2],
       [3, 4]]), ', type = ', <type 'numpy.ndarray'>)


In [0]:
# shape of numpy arrays
a1.shape, a2.shape, a3.shape, a4.shape

((2,), (2,), (2,), (2, 2))

In [0]:
# dimension of numpy arrays
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 1, 1, 2)

In [0]:
# size of numpy arrays
a1.size, a2.size, a3.size, a4.size

(2, 2, 2, 4)

In [0]:
# dtype of numpy arrays
a1.dtype, a2.dtype, a3.dtype, a4.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [9]:
# reshape의 또 다른 사용 방법 
a4r = array(range(1,5)).reshape(-1,2)
a4r
a4r.shape, a4r.ndim, a4r.size, a4r.dtype

((2, 2), 2, 4, dtype('int64'))

In [10]:
a4r = array(range(1,11)).reshape(-1,2)
a4r
a4r.shape, a4r.ndim, a4r.size, a4r.dtype

((5, 2), 2, 10, dtype('int64'))

데이터형이 배정도 실수인 3X4 2차원 배열을 만드시오.

In [12]:
a5r = array(range(1,13), dtype="float64").reshape(-1,4)
a5r
#a5r.shape, a5r.ndim, a5r.size, a5r.dtype

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### numpy

numpy의 개념과 numpy가 필요한 이유, numpy를 이용하여 벡터와 matrix 즉, 행렬을 만들고 이를 상호변환 시킬 수 있는 API를 사용하는 방법에 대해 알아본다.

#### numpy의 개념, 그리고 numpy를 사용하는 이유

- **numpy**

    * numpy는 머신러닝 코드 개발을 할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요한 라이브러리다.  
    * 벡터와 행렬을 이용하면 수치계산이 매우 빨리 수행된다.



- numpy array vs. list

    *  머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지 데이터를 행렬(matrix)로 변환하는 것이 중요하다.
    *  행렬을 나타내기 위해서는 list를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에 **행렬 연산을 위해서는 numpy 사용이 필수적**이다.



In [0]:
# 행렬연산


# A = (1 0)    B = (1 1)
#     (0 1)        (1 1)

# 각 요소의 인덱스에 맞춰서, 즉 원소별로  연산이 수행된다.
# A + B = (2 1)
#         (1 2)

In [0]:
import numpy as np # 라이브러리의 별명을 지정하는 방식을 사용

In [14]:
# 리스트로 행렬 표현

A = [ [1,0], [0,1] ]
B = [ [1,1], [1,1] ]

A + B   # 행렬 연산이 아닌 리스트 연산으로 리스트가 확장된다.

[[1, 0], [0, 1], [1, 1], [1, 1]]

=> 리스트 연산이 됨

In [15]:
# numpy matrix, 직관적임

A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,1] ])

A + B  # 행렬 연산

array([[2, 1],
       [1, 2]])

In [0]:
# A,B
print(A)
print(B)

[[1 0]
 [0 1]]
[[1 1]
 [1 1]]


=>  numpy로 행렬 선언 및 연산을 하였기 때문에 행렬 연산의 결과가 나옴

### numpy vector(1차원 배열)

#### 벡터 생성

- **벡터(vector) 생성**


> 벡터는 np.array([...])를 사용하여 생성한다.

        예) import numpy as np

> 머신러닝 코드 구현 시, 연산을 위해서 벡터, matrix 등의 구조(shape), 차원(dimension)을 확인하는 것이 필요하다.




In [16]:
A = np.array([1,2,3])
B = np.array([4,5,6])

# vector A, B 출력
print("A = ", A, ", B = ", B)

# vector A, B 구조 출력 => shape
print("A.shape = {0}, B.shape =  {1}".format(A.shape, B.shape))

# vector A, B 차원 출력 => ndim
print("A.ndim = {0}, B.ndim = {1}".format(A.ndim, B.ndim))

('A = ', array([1, 2, 3]), ', B = ', array([4, 5, 6]))
A.shape = (3,), B.shape =  (3,)
A.ndim = 1, B.ndim = 1


##### A, B는 항목(즉 요소)가 세개인 벡터임.

> [행벡터](https://terms.naver.com/entry.nhn?docId=3338356&cid=47324&categoryId=47324) vs. [열벡터](https://terms.naver.com/entry.nhn?docId=3338418&ref=y&cid=47324&categoryId=47324)  
>> 그러면 일반 벡터인 A, B를 열벡터 또는 행벡터로 변경하는 방법은?

In [0]:
A.shape, B.shape  # , B는 항목(즉 요소)가 세개인 벡터

((3,), (3,))

#### 열벡터로 변환

In [25]:
A[:, np.newaxis]   # 열벡터

array([[1],
       [2],
       [3]])

In [26]:
A[:, np.newaxis].shape

(3, 1)

In [27]:
A1  = A[:, np.newaxis]
A1.shape

(3, 1)

#### 행벡터로 변환

In [20]:
B[np.newaxis,:]   # 행벡터

array([[4, 5, 6]])

In [21]:
B[np.newaxis,:].shape

(1, 3)

In [22]:
B1  = B[np.newaxis,:]
B1.shape

(1, 3)

In [28]:
print(A,B)
A1,B1

(array([1, 2, 3]), array([4, 5, 6]))


(array([[1],
        [2],
        [3]]), array([[4, 5, 6]]))

In [0]:
A.shape, B.shape, A1.shape, B1.shape

> **reshape()**를 이용해서 벡터형태 변형도 가능하다.
- A.reshape(3,1)
- A.reshape(1,3)

In [29]:
A = np.array([1,2,3])
A, A.reshape(3,1), A.reshape(1,3)  # A는 기본 A.reshape(3,1)은 3행 1열로 표시 A.reshape(1,3)은 1행 3열로 표시

(array([1, 2, 3]), array([[1],
        [2],
        [3]]), array([[1, 2, 3]]))



---



#### 벡터 산술연산

- **벡터 산술연산**


> 벡터 간 산술연산 (+, -, x, /, %)는 벡터의 각각의 원소에 대해서 행해진다.



In [31]:
# vector 산술 연산 (elementwise operation)
# 벡터는 1차원 배열!
A = np.array([1,2,3])
B = np.array([4,5,6])

print("A+B = ", A+B)
print("A-B = ", A-B)
print("A*B = ", A*B)
print("A/B = ", A/B)
print("A%B = ", A%B)

('A+B = ', array([5, 7, 9]))
('A-B = ', array([-3, -3, -3]))
('A*B = ', array([ 4, 10, 18]))
('A/B = ', array([0, 0, 0]))
('A%B = ', array([1, 2, 3]))


In [32]:
B%A

array([0, 1, 0])

In [33]:
A**B

array([  1,  32, 729])

### numpy matrix (2차원 행렬)

#### 행렬 생성

- **행렬 생성**


> matrix는 벡터와 마찬가지로 np.array([ [...], [...], ... ])를 사용하여 생성한다.


>     예)  import numpy as np


          A = (1 2 3)       B = (-1 -2 -3)
              (4 5 6)           (-4 -5 -6)
            shape 2x3       shape 2x3




In [34]:
A = np.array([ [1,2,3], [4,5,6] ])
B = np.array([ [-1,-2,-3], [-4,-5,-6] ])

# vector A, B 구조 출력 => shape
print("A.shape = {0}, B.shape =  {1}".format(A.shape, B.shape))

# vector A, B 차원 출력 => ndim
print("A.ndim = {0}, B.ndim = {1}".format(A.ndim, B.ndim))

A.shape = (2, 3), B.shape =  (2, 3)
A.ndim = 2, B.ndim = 2


#### 형 변환 (reshape)

- **형 변환 (reshape)**


> 벡터를 matrix로 변경하거나 matrix를 다른 구조의 matrix로 변경하기 위해서는 reshape() 사용하여 행렬의 shape를 변경하여야 한다.

           예) D = (1 2 3)   D.reshape(3,2) = (1 2)
                   (4 5 6)                    (3 4)
                                              (5 6)
                shape 2x3             shape 3x2

In [35]:
# reshape()를 이용한 열벡터 생성

C = np.array([1,2,3])  # 기본 벡터

# 벡터 C의 구조 출력 => shape
print("C.shape = ", C.shape)

# 벡터를 (3,1) 행렬로 형 변환 => 열벡터로 변환
C1 = C.reshape(3,1)

print("C1.shape = ", C1.shape)

# 벡터를 (1,3) 행렬로 형 변환 => 행벡터로 변환
C2 = C.reshape(1,3)

print("C2.shape = ", C2.shape)

('C.shape = ', (3,))
('C1.shape = ', (3, 1))
('C2.shape = ', (1, 3))


In [36]:
# reshape()를 이용한 전치행렬 생성

D = np.array([ [1,2,3], [4,5,6] ])  # (2,3) 행렬

# 배열 D의 구조 출력 => shape
print("D.shape = ", D.shape)

# 배열 D를 (3,2) 행렬로 형 변환 
D1 = D.reshape(3,2)

print("D1.shape = ", D1.shape)

# D와 D1 출력
print(D)
print(D1)

('D.shape = ', (2, 3))
('D1.shape = ', (3, 2))
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpy 행렬 곱 (dot product)

#### 행렬 곱 (dot product)

- **행렬 곱 (dot product)**


> A 행렬과 B 행렬의 행렬 곱 (dot product)는 np.dot(A,B)로 나타내며, 행렬 A의 열벡터와 B 행렬의 행벡터가 같아야 한다.


> 만약 같지 않으면 **reshape 또는 전치행렬(transpose) 등을 사용하여 형 변환을 한 후에 행렬 곱을 실행**해야 한다.





In [38]:
A = np.array([ [1,2,3], [4,5,6] ]) # 2x3 행렬
B = np.array([ [-1,-2], [-3,-4], [-5,-6] ]) # 3x2 행렬
print(A)
print(B)
# (2x3) dot product (3x2) == (2x2) 행렬
C = np.dot(A, B) # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape = ", A.shape, ", B.shape = ", B.shape)
print("C.shape = ", C.shape)
print(C)

[[1 2 3]
 [4 5 6]]
[[-1 -2]
 [-3 -4]
 [-5 -6]]
('A.shape = ', (2, 3), ', B.shape = ', (3, 2))
('C.shape = ', (2, 2))
[[-22 -28]
 [-49 -64]]


** 주의

>    A     x    B   =  C  
> (2x**3) x (3**x2) = (2x2)

=> 이렇듯 행렬 A의 열의 수와  B의 행의 수가 같아야 한다!

#### 행렬 곱 (dot product) (ll)

행렬 곱은 사칙연산과는 다른 특징을 가진다.

- 행렬 곱은 행렬의 원소 개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어나


> 1.   행렬 곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고
2.   행렬 곱을 연속으로 계산하면서
3. 결괏값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용된다.

        예) 입력 행렬 형상이 64X64이고, 결과 행렬 형상이 64X10이라면, 중간에 dot product 를 만족시키는 어떤 형상의 행렬이라도 가질 수 있다.
        
> 행렬 곱을 사용하지 않고 산술 연산만 가능하다면, 입력 행렬의 64X64 크기를 가지는 특성 값만을 사용해야 하기 때문에 다양한 특성을 갖는 필터 개발이 불가능하다.

### numpy broadcast (**브로드캐스트**)

- 행렬의 사칙연산은 기본적으로 두 개의 행렬 크기가 같은 경우에만 수행할 수 있다.
- 그러나 numpy에서는 **크기가 다른 두 행렬간에도 사칙연산(+,-,x,/)를 사용할 수 있는데 이를 브로드캐스트(broadcast)**라고 지칭한다.
- 브로드캐스트는 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산된다.

In [39]:
A = np.array([ [1,2], [3,4] ])
b = 5

print(A+b)

[[6 7]
 [8 9]]


=> b가 2x2 행렬로 바뀐다.


>      b = 5   =>   (5 5)
                  (5 5)

In [40]:
C = np.array([ [1,2], [3,4] ])
D = np.array([4,5]) # 2x2로 변환되서 계산된다.

print(C+D)

[[5 7]
 [7 9]]


=> D가 2x2 행렬로 바뀐다.


>      D = (4 5)  =>  (4 5)
                    (4 5)



- **브로드캐스트는 사칙연산에만 사용된다**는 것을 반드시 기억할 것! **행렬 곱에는 적용안됨!!!**

### numpy 전치행렬 (transpose)

- 어떤 행렬의 전치행렬은 원본 행렬의 **열은 행으로, 행은 열로** 바꾼 것이다.
- 원본 행렬을 A라고 하면 전치행렬은 **A.T** 로 나타낸다.
- 즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미한다.



In [41]:
A = np.array([ [1,2],[3,4],[5,6] ]) # 3x2행렬
B = A.T  # A의 전치행렬, 2x3행렬

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

('A.shape ==', (3, 2), ', B.shape ==', (2, 3))
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [42]:
# vector 전치행렬

C = np.array([1,2,3,4,5]) # vector, matrix 아님
D = C.T  # C는 벡터이므로 transpose 안됨

E = C.reshape(1,5) # 1x5 matrix
F = E.T  # E의 전치행렬

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(E)
print(F)

('C.shape ==', (5,), ', D.shape ==', (5,))
('E.shape ==', (1, 5), ', F.shape ==', (5, 1))
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### numpy 행렬 원소 접근

####  indexing & slicing

- **행렬 원소 접근(l)**


> 행렬 원소를 명시적(explicit)으로 접근하기 위해서는 리스트에서처럼, 인덱싱 & 슬라이싱 모두 사용이 가능하다.

          예1) A[0,0] 또는 A[0][0]은 1행 1열, A[2,1] 또는 A[2][1]은 3행 2열임
          예2) A[ : , 0] 은 모든 행 1열을 나타냄
          예3) A[0:-1, 1:2] 인덱스 0인 1행부터 인덱스 -1-1=-2인 2행까지의 모든 데이터,
                            그리고 인덱스 1인 2열부터 인덱스 2-1=1인 2열까지의 모든 데이터
          예4) A[ :, : ] 은 모든 행, 모든 열



In [43]:
# 예제1

A = np.array([10,20,30,40,50,60]).reshape(3,2)

print("A.shape = ", A.shape)
print(A)
A

('A.shape = ', (3, 2))
[[10 20]
 [30 40]
 [50 60]]


array([[10, 20],
       [30, 40],
       [50, 60]])

In [44]:
# 예제2 - 인덱싱

print("A[0,0] ==", A[0,0], ", A[0][0] ==", A[0][0])
print("A[2,1] ==", A[2,1], ", A[2][1] ==", A[2][1])

('A[0,0] ==', 10, ', A[0][0] ==', 10)
('A[2,1] ==', 60, ', A[2][1] ==', 60)


In [45]:
# 예제3 - 슬라이싱

print("A[0:-1, 1:2] ==", A[0:-1, 1:2])  # == A[0:2, 1:2]

('A[0:-1, 1:2] ==', array([[20],
       [40]]))


In [46]:
A[0:2, 1:2]

array([[20],
       [40]])

In [47]:
# 예제4 - 슬라이싱

print("A[ :, 0] ==", A[:, 0])
print("A[ :, :] ==", A[:, :])

('A[ :, 0] ==', array([10, 30, 50]))
('A[ :, :] ==', array([[10, 20],
       [30, 40],
       [50, 60]]))


#### iterator

- **행렬 원소 접근(ll)**


> 명시적(explicit) 인덱싱 & 슬라이싱 이외에 **행렬 모든 원소를 access하는 경우에는 iterator** 사용이 가능하다.


> numpy iterator는 C++, Java iterator처럼 next() 메서드를 통해,                     
                데이터값을 처음부터 끝까지 순차적으로 읽어들이는 방법을 제공한다.





In [48]:
import numpy as np

A = np.array([ [10,20,30,40], [50,60,70,80] ])

print(A)
print("A.shape = ", A.shape)


[[10 20 30 40]
 [50 60 70 80]]
('A.shape = ', (2, 4))


In [49]:
# 행렬 A의 iterator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  
  idx = it.multi_index
  
  print("current value => ", A[idx])
  
  it.iternext()

('current value => ', 10)
('current value => ', 20)
('current value => ', 30)
('current value => ', 40)
('current value => ', 50)
('current value => ', 60)
('current value => ', 70)
('current value => ', 80)


2x4 행렬인 경우,

> (0,0) => (0,1) => (0,2) => (0,3) => (1,0) => (1,1) => (1,2) => (1,3)   순서대로 access
 




---

